### ISSUE TITLE
Create no-sdk branch

### ISSUE THREAD

**Issue by victorpopkov** [dstmodders/mod-keep-following#24]
### Problem

As we migrate to the new SDK in the [main] branch, it has become challenging to continue developing and maintaining the project without fully adopting the SDK. This issue is slowing down progress on non-SDK-related features and bug fixes.

### Proposed Solution

Create a separate [no-sdk] branch based on the latest public release [v0.21.0] that retains the codebase without the new SDK. This branch would allow for continued development and maintenance independently of the SDK migration, ensuring that progress on other features isn't hindered.

Additionally, we need to apply corresponding updates to the maintenance workflows, as there have been significant changes in the [main] branch.

### Action Plan

- [x] Create the [no-sdk] branch
- [x] Update [GitHub Actions Workflows](https://github.com/dstmodders/mod-keep-following/tree/main/.github/workflows) to align with our latest conventions
- [x] Update code quality related configurations
- [x] Fix code quality issues 
- [x] Update documentation to align with our latest conventions
- [x] Implement Continuous Deployment (CD) for the [no-sdk] documentation, making it available at https://docs.dstmodders.com/keep-following/no-sdk/

[main]: https://github.com/dstmodders/mod-keep-following/tree/main
[no-sdk]: https://github.com/dstmodders/mod-keep-following/tree/no-sdk
[v0.21.0]: https://github.com/dstmodders/mod-keep-following/tree/v0.21.0

**Comment by victorpopkov** [comment]
Respectively, for the development [develop-no-sdk](https://github.com/dstmodders/mod-keep-following/tree/develop-no-sdk) branch has also been created.
